clients/urls.py
from django.contrib import admin
# -> views de autenticacao, login e logout, para funcionarem faça os htmls
from django.contrib.auth import views as auth_views
from django.urls import path, include

# para o django servir imagens (static files) em debug mode
# to serve files uploaded by a user during development > https://docs.djangoproject.com/en/3.2/howto/static-files/
# from django.conf import settings
# from django.conf.urls.static import static


urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('core.urls')),
    path('login/', auth_views.LoginView.as_view(), name='login'),
    # -> o django ja sabe que e uma view
    path('logout/', auth_views.LogoutView.as_view(), name='logout'),
]
# + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT) # Return a URL pattern for serving files in debug mode
# dessa forma esta-se concatenando as urls existentes, novas url'patterns'
# dos arquivos estaticos, nesse caso

core/urls.py
from django.urls import path
from . import views

app_name = 'core'
urlpatterns = [
    path('', views.list_clients, name='list_clients'),
    path('new/', views.new_client, name='new_client'),
    path('update/<int:id>/', views.update_client, name='update_client'),
    path('delete/<int:id>/', views.delete_client, name='delete_client'),
    path('id/', views.list_id, name='list_id'),
    path('new_id/', views.new_id, name='new_id'),
    path('update_id/<int:id>/', views.update_id, name='update_id'),
    path('delete_id/<int:id>/', views.delete_id, name='delete_id'),
]

core/models.py
from django.db import models


class ID(models.Model):  # -> example of one to one relationship
    number = models.CharField(
        verbose_name='Doc id',
        max_length=50,
        unique=True)

    def __str__(self):
        return self.number


class Client(models.Model):
    name = models.CharField(verbose_name='Nome', max_length=70)
    last_name = models.CharField(
        verbose_name='Sobrenome',
        max_length=72,
        null=True)
    age = models.IntegerField(verbose_name='Idade')
    salary = models.DecimalField(
        verbose_name='Salario',
        max_digits=7,
        decimal_places=2)
    email = models.EmailField(verbose_name='E-mail', null=True, blank=True)
    photos = models.ImageField(
        verbose_name='Fotos',
        null=True,
        blank=True,
        upload_to='media/')
    dt_birth = models.DateField(
        verbose_name='Data de nascimento',
        null=True,
        blank=True)
    # -> CASCADE vai apagar o client se apagar o ID
    doc_id = models.OneToOneField(ID, null=True, on_delete=models.SET_NULL)
    # -> mas a ideia ainda prevalece, cada Client tem que ter apenas um ID, que sera so seu

    class Meta:
        verbose_name = 'Cliente'

    def __str__(self):
        return self.name + ' ' + self.last_name


class Product(models.Model):  # -> example of many to many
    description = models.CharField(verbose_name='Descricao', max_length=100)
    price = models.DecimalField(
        verbose_name='preco',
        max_digits=7,
        decimal_places=2)
    taxes = models.DecimalField(
        verbose_name='taxas',
        max_digits=7,
        decimal_places=2)

    class Meta:
        verbose_name = 'Produto'

    def __str__(self):
        return self.description


class Sale(models.Model):  # -> example of one to many (foreign key) relationship
    sale_number = models.CharField(
        verbose_name='Numero do vendedor',
        max_length=10,
        unique=True)
    # -> varios vendedores para um cliente
    client = models.ForeignKey(Client, null=True, on_delete=models.SET_NULL)
    date = models.DateTimeField(verbose_name='Data', auto_now_add=True)
    total = models.DecimalField(
        verbose_name='Total',
        max_digits=7,
        decimal_places=2)
    products = models.ManyToManyField(Product, blank=True)

    class Meta:
        verbose_name = 'Vendedor'

    def __str__(self):
        return self.sale_number

core/forms.py
from django.forms import ModelForm
from .models import Client, ID


class ClientForm(ModelForm):
    class Meta:
        model = Client
        fields = [
            'name',
            'last_name',
            'age',
            'salary',
            'email',
            'photos',
            'dt_birth',
            'doc_id']


class IdForm(ModelForm):
    class Meta:
        model = ID
        fields = ['number']

core/views.py
from django.shortcuts import render, redirect, get_object_or_404
from .models import Client, ID
from .forms import ClientForm, IdForm
# -> para limitar o acesso a certas views a usuarios com sessoes logadas
from django.contrib.auth.decorators import login_required


# Client's views
# C: Create
@login_required
def new_client(request):
    form = ClientForm()

    if request.method == 'POST':
        form = ClientForm(request.POST, request.FILES)
        if form.is_valid():
            form.save()
            return redirect('core:list_clients')

    context = {
        'form': form,
    }
    return render(request, 'form.html', context=context)


# R: Read
def list_clients(request):
    clients = Client.objects.all()
    context = {
        'clients': clients,
    }
    return render(request, 'clients.html', context=context)


# U: Update
@login_required
def update_client(request, id):
    client = get_object_or_404(Client, pk=id)
    # criara o form com informacoes predefinidas o client
    form = ClientForm(request.POST or None, request.FILES or None, instance=client)

    if form.is_valid():
        form.save()
        return redirect('core:list_clients')

    context = {
        'form': form,
        'update': 1,
    }
    return render(request, 'form.html', context=context)


# D: Delete
@login_required
def delete_client(request, id):
    client = get_object_or_404(Client, pk=id)

    if request.method == 'POST':  # ->so caira aqui quando clicar em apagar que mandara um post aqui
        client.delete()
        return redirect('core:list_clients')

    context = {
        'client': client,
    }
    # -> so chega aqui com metodo get pois e apenas uma requisicao
    return render(request, 'confirm.html', context=context)


# Id's views
# C: Create
@login_required
def new_id(request):
    form = IdForm(request.POST or None)

    if form.is_valid():
        form.save()
        return redirect('core:list_id')

    context = {
        'form': form,
    }
    return render(request, 'form.html', context=context)


# R: Read
@login_required
def list_id(request):
    doc_ids = ID.objects.all()
    context = {
        'id': doc_ids,
    }
    return render(request, 'clients_id.html', context=context)


# U: Update
@login_required
def update_id(request, id):
    doc_id = get_object_or_404(ID, pk=id)
    form = IdForm(request.POST or None, instance=doc_id)

    if form.is_valid():
        form.save()
        return redirect('core:list_id')

    context = {
        'form': form,
        'update': 1,
    }
    return render(request, 'form.html', context=context)


# D: Delete
@login_required
def delete_id(request, id):
    doc_id = get_object_or_404(ID, pk=id)

    if request.method == 'POST':
        doc_id.delete()
        return redirect('core:list_id')

    context = {
        'id': doc_id,
    }
    return render(request, 'confirm.html', context=context)

core/templates/clients.html
{% extends 'base.html' %}

{% block title %} Clientes {% endblock %}

{% block content %}

<div class="p-5 mb-4 bg-light rounded-3">
    <div class="container-fluid py-5">

        <div class="row">
            <div class="display-5 fw-bold lh-1 mb-3">
                <div class="col-lg-7 text-center text-lg-start">
                    <h1 class="display-4 fw-bold lh-1 mb-3">Clientes</h1>
                </div>
                {% if user.is_authenticated %}
                    <div class="col-lg-7 text-center text-lg-start">
                        <p class="lead"> Bem-vindo {{ user.username|capfirst }} </p>
                    </div>
                    <div class="d-grid gap-2 d-sm-flex justify-content-sm-end">
                        <a class="btn btn-secondary btn-sm px-4 gap-3" href="{% url 'core:list_id' %}">Ver doc IDs</a>
                        <a class="btn btn-danger btn-sm px-4" href="{% url 'logout' %}">Log out</a>
                    </div>
                {% else %}
                    <div class="d-grid gap-2 d-sm-flex justify-content-sm-end">
                        <a class="btn btn-success px-4" href="{% url 'login' %}">Log in</a>
                    </div>
                {% endif %}
                <hr>
            </div>
        </div>

        <div class="row">
            <ul class="list-group list-group-numbered d-flex">
            {% for client in clients %}
                <li class="list-group-item d-flex justify-content-evenly align-items-center">
                    <p class="flex-grow-1 m-1">{{ client }}</p>
                    {% if user.is_authenticated %}
                        <a class="btn btn-info m-1" href="{% url 'core:update_client' client.id %}">Editar</a>
                        <a class="btn btn-danger m-1" href="{% url 'core:delete_client' client.id %}">Excluir</a>
                    {% endif %}
                </li>
            {% endfor %}
            </ul>
            {% if user.is_authenticated %}
            <div class="d-grid gap-2 d-sm-flex justify-content-sm-start">
                <a class="btn btn-primary my-3" href="{% url 'core:new_client' %}">Cadastrar novo cliente</a>
            </div>
            {% endif %}
        </div>

    </div>
</div>

{% endblock %}

core/templates/clients_id.html
{% extends 'base.html' %}

    {% block title %} IDs {% endblock %}

{% block content %}

<div class="p-5 mb-4 bg-light rounded-3">
    <div class="container-fluid py-5">

        <div class="row">
            <div class="display-5 fw-bold lh-1 mb-3">
                <div class="col-lg-7 text-center text-lg-start">
                    <h1 class="display-5 fw-bold">Doc IDs disponíveis</h1>
                </div>
                {% if user.is_authenticated %}
                    <div class="col-lg-7 text-center text-lg-start">
                        <p class="lead"> Olá {{ user.username|capfirst }} </p>
                    </div>
                    <div class="d-grid gap-2 d-sm-flex justify-content-sm-end">
                        <a class="btn btn-danger btn-sm px-4" href="{% url 'logout' %}">Log out</a>
                    </div>
                {% else %}
                    <div class="alert alert-danger">
                        <p>Você precisa fazer login para continuar!</p>
                        <hr>
                        <a class="btn btn-success m-3" href="{% url 'login' %}">Log in</a>
                    </div>
                {% endif %}
                <hr>
            </div>
        </div>

        {% if user.is_authenticated %}
            <div class="row">
                    <ul class="list-group list-group-numbered d-flex">
                    {% for loc_id in id %}
                        <li class="list-group-item d-flex justify-content-evenly align-items-center">
                            <p class="flex-grow-1 m-1">{{ loc_id }}</p>
                            <a class="btn btn-info m-1" href="{% url 'core:update_id' loc_id.id %}">Editar</a>
                            <a class="btn btn-danger m-1" href="{% url 'core:delete_id' loc_id.id %}">Excluir</a>
                        </li>
                    {% endfor %}
                    </ul>
                    <div class="d-grid gap-2 d-sm-flex justify-content-sm-start">
                        <div class="btn-group mt-4" role="group">
                            <a class="btn btn-primary my-3" href="{% url 'core:new_id' %}">Cadastrar novo ID</a>
                            <a class="btn btn-secondary my-3" href="{% url 'core:list_clients' %}">Voltar</a>
                        </div>
                    </div>
            </div>
        {% endif %}
        
    </div>
</div>

{% endblock %}

core/templates/confirm.html
{% extends 'base.html' %}

{% block title %} Confirmação de exclusão {% endblock %}

{% block content %}

<div class="p-5 mb-4 bg-light rounded-3">
  <div class="container-fluid py-5 text-center">
    <h1 class="display-6 mb-5 fw-bold">
      Excluir {% if client.name %} cliente {{ client.name }} {% else %} doc ID {{ id.number }} {% endif %}?
    </h1>

    <form method="POST">
      {% csrf_token %}
      <div class="form-group">
        <div class="btn-group" role="group">
          <button class="btn btn-danger" type="submit">Excluir</button>
          {% if client.name %}
            <a class="btn btn-primary" href="{% url 'core:list_clients' %}">Cancelar</a>
          {% else %}
            <a class="btn btn-primary" href="{% url 'core:list_id' %}">Cancelar</a>
          {% endif %}
      </div>
      </div>
    </form>

  </div>
</div>

{% endblock %}

core/templates/form.html
{% extends 'base.html' %}
{% load bootstrap %}
<!-- Esse formulario serve para o client_id e para o client -->
    {% block title %}
        Novo {% if form.name %} Cliente {% else %} Doc ID {% endif %}
    {% endblock %}

{% block content %}

<div class="p-5 mb-4 bg-light rounded-3">
    <div class="container-fluid py-5">
        <div class="col-lg-7 text-center text-lg-start">
            {% if update %} 
                <h1 class="display-5 mb-4 fw-bold">
                    Atualização de {% if form.name %} dados do cliente {% else %} doc ID {% endif %}
                </h1>
            {% else %}
                <h1 class="display-5 mb-4 fw-bold">
                    Novo {% if form.name %} cliente {% else %} doc ID {% endif %}
                </h1>
            {% endif %}
        </div>
        <!-- <form> that posted the request must have the attribute enctype="multipart/form-data". Otherwise, request.FILES will be empty. -->
        <form method="post" action="" enctype="multipart/form-data">
            {% csrf_token %}
            <!-- form.as_p make the form view use paragraphs, it will be shown verticaly -->
            {{ form|bootstrap }}
            <div class="d-grid gap-2 d-sm-flex justify-content-sm-start">
                <div class="btn-group mt-4" role="group">
                    <button type="submit" class="btn btn-success">Salvar</button>
                    {% if form.name %}
                            <a class="btn btn-danger" href="{% url 'core:list_clients' %}">Cancelar</a>
                    {% else %}
                            <a class="btn btn-danger" href="{% url 'core:list_id' %}">Cancelar</a>
                    {% endif %}
                </div>
            </div>
        </form>
    </div>
</div>

{% endblock %}